{% set version = "1.3.0" %}
{% set checksum = "f775de089bfa37e9eec4ec46ce960ab1b2e06d00c8cac4798190ff60680e40dc" %}

package:
  name: z5py
  version: {{ version }}

source:
    url: https://github.com/constantinpape/z5/archive/{{ version }}.tar.gz
    sha256: {{ checksum }}

build:
  number: 1000
  skip: True  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - boost-cpp
    - numpy
    - xtensor >=0.18.1,<0.19
    - xtensor-python >=0.21,<0.22
    - blosc
    - bzip2
    - xz
    - zlib
    - nlohmann_json
  run:
    - python
    - boost-cpp
    - {{ pin_compatible('numpy') }}
    - blosc
    - bzip2
    - xz
    - zlib
    - six
    - futures  # [py27]

test:
  imports:
    - z5py
  source_files:
    - src/python/test/*.py
  commands:
    - python -m unittest discover -s src/python/test -v

about:
  home: https://github.com/constantinpape/z5
  license: MIT
  license_file: LICENSE
  summary: Lightweight C++ and Python interface for datasets in zarr and N5 format.

extra:
  recipe-maintainers:
    - constantinpape
    - SylvainCorlay
