{% set version = "1.4.1" %}
{% set checksum = "0efc03aa7a42811e6630aa3ca7fa717df7824feeb9fd5e216e5739ba5f763403" %}

package:
  name: z5py
  version: {{ version }}

source:
    url: https://github.com/constantinpape/z5/archive/{{ version }}.tar.gz
    sha256: {{ checksum }}

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - boost-cpp
    - numpy
    - xtensor >=0.19,<0.20
    - xtensor-python >=0.22,<0.23
    - xsimd >=7,<8
    - blosc
    - bzip2
    - xz
    - zlib
    - nlohmann_json
  run:
    - python
    - boost-cpp
    - {{ pin_compatible('numpy') }}
    - blosc
    - bzip2
    - xz
    - zlib
    - six
    - futures  # [py27]

test:
  imports:
    - z5py
  source_files:
    - src/python/test/*.py
  commands:
    - python -m unittest discover -s src/python/test -v

about:
  home: https://github.com/constantinpape/z5
  license: MIT
  license_file: LICENSE
  summary: Lightweight C++ and Python interface for datasets in zarr and N5 format.

extra:
  recipe-maintainers:
    - constantinpape
    - SylvainCorlay
