travis:
  secure:
    BINSTAR_TOKEN: WuXwKyDHZtcbjNhbxYPJlw71h9vLaqbE5/rKIzYN50g0sFBSyw7YINKEbpcFQT2nNfvBkcQEwC2cLct6rKux/B/plXc8+UrrRgsJsuErrWqWfDUaz26J7kFgafdO3J+QOfsO2TXpeOrIDn3GS/DTpLFJsrcIdwB8Qn5Jd5XJ7kolcn7GK5VxYRTIwl8rvzWJWM4zx0Z3/uEltOqUw2zhLF67CiJl5E7WWn+SqPi2wMqd4QxI0ln1S97l9GUkF7UZHZosXJkx4bOtEYWluOFIJfwcHOiWWiER4KY+LchpDxxyDXcWlhKzasdhw04xHDr68Ojz9sToxadW5R7H90dih1jOHgE4D2tOPH1tz727p4+XxSRz058Ks6uf2F4+zg7Y+x+nogFalrIO8gJBOvOoq5OdznD6AI98six/1PTPjIXbr3TEsI8wuei1WdcfGHSIAc2Z6M1Qw4togGrwig6L1IIzLDz9FkI8UnlsBVyUpki1wwFocqUrfhbMATtFdGuMM9amxmPae3szp4XVLA4HXwK59YJoBo94dqLFZ6Ds7yXtlq50reP+4ijGKA+flw2TOrKKjan1aeyhXCBkEE2b7AtmDuiXPfKFujWkyS8TNKGYUNC7mZhD7BF7hLPWusqOfieNx7Xd01t9Q9z6+ZEAPTVjydm1nmLzZQMaE0Ax1OM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
